name: 部署到 Cloudflare Pages

on:
  push:
    branches:
      - main  # 当代码推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出代码库
      - name: 检出代码库
        uses: actions/checkout@v3

      # 第二步：安装 pnpm
      - name: 安装 pnpm
        run: |
          curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
          pnpm setup  # 设置 pnpm 全局路径
        shell: bash

      # 第三步：安装依赖
      - name: 安装依赖
        run: pnpm install  # 使用 pnpm 安装依赖

      # 第四步：构建项目
      - name: 构建项目
        run: pnpm run docs:build  # 使用 pnpm 构建项目

      # 第五步：全局安装 Wrangler
      - name: 全局安装 Wrangler
        run: pnpm add -g wrangler  # 使用 pnpm 全局安装 Wrangler

      # 第六步：发布到 Cloudflare Pages
      - name: 发布到 Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}  # 在 GitHub Secrets 中配置你的 Cloudflare API Token
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}  # 在 GitHub Secrets 中配置你的 Cloudflare Account ID
          projectName: study-wiki  # Cloudflare Pages 项目名称
          directory: docs/.vitepress/dist  # 替换为 VitePress 构建输出的目录
