name: 部署到 Cloudflare Pages

# 当推送到 main 分支时触发
on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出代码
      - name: 检出代码
        uses: actions/checkout@v3

      # 第二步：安装 pnpm
      - name: 安装 pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest  # 安装最新版本的 pnpm

      # 第三步：安装依赖
      - name: 安装依赖
        run: pnpm install  # 使用 pnpm 安装依赖

      # 第四步：构建项目
      - name: 构建项目
        run: pnpm run docs:build  # 构建 VitePress 项目

      # 第五步：检查构建输出目录
      - name: 检查构建输出
        run: ls -alh docs/.vitepress/dist  # 列出构建后的文件，确保生成正确

      # 第六步：发布到 Cloudflare Pages
      - name: 发布到 Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN }}  # Cloudflare Pages API Token
          accountId: ${{ secrets.CLOUDFLARE_PAGES_ACCOUNT }}  # Cloudflare 账户 ID
          projectName: study-wiki  # 替换为你的 Cloudflare Pages 项目名称
          directory: docs/.vitepress/dist  # 确保这是构建后的输出目录
