name: 部署到 Cloudflare Pages

on:
  push:
    branches:
      - main  # 当代码推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出代码库
      - name: 检出代码库
        uses: actions/checkout@v3

      # 第二步：安装 pnpm 并设置 SHELL 环境变量
      - name: 安装 pnpm
        run: |
          curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
          pnpm setup
        shell: bash
        env:
          SHELL: /bin/bash  # 设置 SHELL 环境变量为 bash

      # 第三步：将 pnpm 的全局路径添加到环境变量 PATH 中
      - name: 添加 pnpm 到 PATH
        run: echo "::add-path::$(pnpm env get-bin-path)"

      # 第四步：安装依赖
      - name: 安装依赖
        run: pnpm install

      # 第五步：构建项目
      - name: 构建项目
        run: pnpm run docs:build  # 使用 pnpm 构建 VitePress 项目

      # 第六步：安装 Wrangler (Cloudflare CLI 工具)
      - name: 安装 Wrangler
        run: pnpm add -g wrangler

      # 第七步：发布到 Cloudflare Pages
      - name: 发布到 Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }} # 在 GitHub Secrets 中配置你的 Cloudflare API Token
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} # 在 GitHub Secrets 中配置你的 Cloudflare Account ID
          projectName: study-wiki # 替换为 Cloudflare Pages 项目名称
          directory: docs/.vitepress/dist # 替换为 VitePress 构建输出的目录
