name: 部署到Cloudflare Pages

on:
  push:
    branches:
      - 'main'  # 监听 main 分支的推送

jobs:
  build:
    runs-on: ubuntu-22.04  # 选择 Ubuntu 22.04 作为运行环境

    steps:
      # 第一步：检出代码
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 完整检出代码历史

      # 第二步：安装 pnpm
      - uses: pnpm/action-setup@v3
        with:
          version: latest  # 安装最新版本的 pnpm

      # 第三步：设置 Node.js 环境并启用 pnpm 缓存
      - uses: actions/setup-node@v4
        with:
          cache: pnpm  # 启用 pnpm 缓存，加快依赖安装速度

      # 第四步：安装依赖
      - name: 安装依赖
        run: pnpm install  # 使用 pnpm 安装依赖

      # 第五步：构建项目
      - name: 构建项目
        run: pnpm build  # 构建 VitePress 文档
        env:
          NODE_OPTIONS: --max_old_space_size=4096  # 增加 Node.js 内存限制

      # 第六步：发布到 Cloudflare Pages
      - name: 发布到 Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}  # 在 GitHub Secrets 中配置你的 Cloudflare API Token
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}  # 在 GitHub Secrets 中配置你的 Cloudflare Account ID
          projectName: study-wiki  # Cloudflare Pages 项目名称
          directory: docs/.vitepress/dist  # 替换为 VitePress 构建输出的目录
