name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main  # 当代码推送到 master 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run docs:build

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Publish to Cloudflare Pages
        run: wrangler pages publish docs/.vitepress/dist --project-name=my-vitepress-site --branch=production
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
