name: 部署到 Cloudflare Pages

on:
  push:
    branches:
      - main  # 当代码推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码库
        uses: actions/checkout@v3

      - name: 安装依赖
        run: npm install

      - name: 构建项目
        run: npm run docs:build

      - name: 全局安装 Wrangler
        run: npm install -g wrangler

      - name: 发布到 Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: study-wiki
          directory: docs/.vitepress/dist
